spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;CASE_INSENSITIVE_IDENTIFIERS=true
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: com.solidcode.offers.util.H2DialectExtended
        globally_quoted_identifiers: true
        ddl-auto: create-drop
        use_sql_comments: false
        format_sql: true
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

unsplash:
  access:
    key: xDmX0hLExU7ZO-7ma0Lw37-fFDLCWrC-TrxcZ4rInQE