name: offers Deploy

on:
  workflow_run:
    workflows: [ "offers ci" ]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull cskoray/offers:latest
      - name: Delete old Docker container
        run: sudo docker rm -f offers-container || true
      - name: Run Docker container
        run: sudo docker run -d --name offers-container -p 8080:8080 cskoray/offers
